// Mocks generated by Mockito 5.4.6 from annotations
// in trab02flutter/test/services/country_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:trab02flutter/models/country.dart' as _i4;
import 'package:trab02flutter/services/country_service_interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ICountryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockICountryService extends _i1.Mock implements _i2.ICountryService {
  MockICountryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Country>> fetchAllCountries() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAllCountries, []),
            returnValue: _i3.Future<List<_i4.Country>>.value(<_i4.Country>[]),
          )
          as _i3.Future<List<_i4.Country>>);

  @override
  _i3.Future<_i4.Country?> fetchCountryByName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#fetchCountryByName, [name]),
            returnValue: _i3.Future<_i4.Country?>.value(),
          )
          as _i3.Future<_i4.Country?>);
}
